# Generated by Django 3.2.7 on 2021-09-30 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgame',
            name='participants',
            field=models.ManyToManyField(to='users.CustomUser', verbose_name='участники игры'),
        ),
        migrations.AddField(
            model_name='quizgame',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_game', to='quiz.quiz', verbose_name='квиз для игры'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='quiz.section', verbose_name='тематика квиза'),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_category', to='quiz.quiz', verbose_name='квиз'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quiz.questioncategory', verbose_name='категории'),
        ),
    ]
