# Generated by Django 3.2.7 on 2021-10-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='hoho', max_length=64, verbose_name='название тематической секции'),
            preserve_default=False,
        ),
    ]
