# Generated by Django 3.2.7 on 2021-10-04 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_quiz_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='название типа вопроса')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='round',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='текущий раунд'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
        migrations.AddField(
            model_name='section',
            name='special_color',
            field=models.CharField(default='blue', max_length=10, verbose_name='цвет тематической секции'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='value',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='стоимость вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.questiontype', verbose_name='тип вопроса'),
            preserve_default=False,
        ),
    ]
