# Generated by Django 3.2.7 on 2021-11-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20211004_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='q_audio/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='q_images/'),
        ),
    ]
