# Generated by Django 3.2.7 on 2021-11-02 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_auto_20211101_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgame',
            name='game_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='ведущий'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.questioncategory', verbose_name='категории'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=64, verbose_name='название'),
        ),
        migrations.CreateModel(
            name='InGameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, verbose_name='текст вопроса')),
                ('value', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='стоимость вопроса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='q_images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='q_audio/')),
                ('fresh', models.BooleanField(default=False, verbose_name='бы ли дан ответ на вопрос')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quiz.questioncategory', verbose_name='категории')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questiontype', verbose_name='тип вопроса')),
            ],
        ),
    ]
