# Generated by Django 3.2.7 on 2021-11-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20211102_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgame',
            name='started',
            field=models.BooleanField(default=False, verbose_name='стартовала ли игра'),
        ),
    ]
