# Generated by Django 3.2.7 on 2021-11-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quizgame_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingamequestion',
            name='fresh',
            field=models.BooleanField(default=True, verbose_name='бы ли дан ответ на вопрос'),
        ),
    ]
