# Generated by Django 3.2.7 on 2021-11-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20211102_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='super_bet',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
