# Generated by Django 3.2.7 on 2021-11-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_participant_super_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='super_answer',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
