# Generated by Django 3.2.7 on 2021-11-04 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_participant_super_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgame',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_game', to='quiz.quiz', verbose_name='квиз для игры'),
        ),
    ]
