# Generated by Django 3.2.7 on 2021-11-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_participant_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='answer_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='correct_answers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
