# Generated by Django 3.2.7 on 2021-11-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20211104_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='answer_time',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='ready',
        ),
        migrations.AddField(
            model_name='quizgame',
            name='room_name',
            field=models.CharField(default='xkgzjv23cju7jtkrnvvdmrk36vps9t', max_length=32),
        ),
    ]
