# Generated by Django 3.2.7 on 2021-11-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20211111_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgame',
            name='room_name',
            field=models.CharField(default='iqrsu1235ijp2zyqiblpn5qm72sup3', max_length=32),
        ),
    ]
