# Generated by Django 3.2.7 on 2021-11-12 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_alter_quizgame_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizgame',
            name='participants',
        ),
        migrations.AddField(
            model_name='participant',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='quiz.quizgame'),
        ),
        migrations.AlterField(
            model_name='quizgame',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_game', to='quiz.quiz', verbose_name='квиз для игры'),
        ),
        migrations.AlterField(
            model_name='quizgame',
            name='room_name',
            field=models.CharField(default='hvet1x081ywo6zdnadv8gx7hsn4zeq', max_length=32),
        ),
    ]
