# Generated by Django 3.2.7 on 2021-11-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_alter_quizgame_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgame',
            name='room_name',
            field=models.CharField(default='y0fksbsq6mkll7i4aug60dt0rrdtjl', max_length=32),
        ),
    ]
