# Generated by Django 3.2.7 on 2021-11-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_alter_quizgame_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgame',
            name='room_name',
            field=models.CharField(default='6lz5025abf8caj4md9hh1d97ztjsjd', max_length=32),
        ),
    ]
