# Generated by Django 3.2.7 on 2021-11-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_alter_quizgame_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgame',
            name='room_name',
            field=models.CharField(default='k1qi6gp4nqgnfelzhszid2kmj399qr', max_length=32),
        ),
    ]
