from django.urls import path

from quiz import views

urlpatterns = [
    path('sections', views.sections, name='sections'),
    path('types', views.types, name='types'),
    path('quiz_list', views.quiz_list, name='quiz_list'),
    path('game_quiz_list', views.game_quiz_list, name='game_quiz_list'),
    path('theme_list', views.theme_list, name='theme_list'),
    path('question_list', views.question_list, name='question_list'),
    path('question_detail', views.question_detail, name='question_detail'),
    path('ig_question_detail', views.ig_question_detail, name='ig_question_detail'),
    path('quiz_cr', views.create_quiz, name='quiz_cr'),
    path('theme_cr', views.create_theme, name='quiz_cr'),
    path('question_cr', views.create_question, name='quiz_cr'),
    path('arrange_round', views.arrange_theme_round, name='arrange_round'),
    path('change_value', views.change_value, name='change_value'),
    path('change_round', views.change_round, name='change_round'),
    path('theme_round', views.theme_round, name='theme_round'),
    path('game_quiz_cr', views.game_quiz_cr, name='game_quiz_cr'),
    path('quiz_game_players', views.quiz_game_players, name='quiz_game_players'),
    path('quiz_game_round', views.quiz_game_round, name='quiz_game_round'),
    path('round_completed', views.round_completed, name='round_completed'),
    path('players_dashboard', views.players_dashboard, name='players_dashboard'),
    path('player_ready', views.player_ready, name='player_ready'),
    path('start_game', views.start_game, name='start_game'),
    path('player_score', views.player_score, name='player_score'),
    path('wrong_answer', views.wrong_answer, name='wrong_answer'),
    path('corr_answer', views.corr_answer, name='corr_answer'),
    path('check_ready_players', views.check_ready_players, name='check_ready_players'),
    path('games_available', views.games_available, name='games_available'),
    path('connect', views.connect, name='connect'),
    path('bet_super', views.bet_super, name='bet_super'),
    path('answer_super', views.answer_super, name='answer_super'),
    path('corr_answer_super', views.corr_answer_super, name='corr_answer_super'),
    path('wrong_answer_super', views.wrong_answer_super, name='wrong_answer_super'),
    path('get_answers', views.get_answers, name='get_answers'),
    path('end_game', views.end_game, name='end_game'),
]